# Generated by Django 5.2.10 on 2026-02-04 20:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('program_workout', models.CharField(default='pushup', max_length=20)),
                ('current_set', models.IntegerField(default=1)),
                ('remaining_reps', models.IntegerField(default=0)),
                ('total_sets', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vision.userfitnessprofile')),
            ],
            options={
                'unique_together': {('profile', 'date')},
            },
        ),
    ]
