# Generated by Django 5.2.10 on 2026-03-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vision", "0002_workoutprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfitnessprofile",
            name="health_issue",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="workoutprogress",
            name="program_workout",
            field=models.CharField(default="squat", max_length=20),
        ),
    ]
